from __future__ import annotations

import argparse
import inspect
import os
from collections.abc import Sequence
from pathlib import Path
from typing import Any, Callable


DEFAULT_MODEL_ID = "unsloth/gemma-4-E2B-it"
DEFAULT_DATASET_PATH = Path("data/finetune/korean_cute_style_train.jsonl")
DEFAULT_OUTPUT_DIR = Path("runs/finetune/korean-cute-lora")
DEFAULT_MAX_SEQ_LENGTH = 1024
DEFAULT_MAX_STEPS = -1
DEFAULT_NUM_TRAIN_EPOCHS = 1.0
DEFAULT_CHAT_TEMPLATE = "gemma-4"
DEFAULT_GPU_MEMORY_UTILIZATION = 0.9
DEFAULT_MIN_VRAM_GB = 8.0


def _parse_args(argv: Sequence[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train a Korean cute-style QLoRA adapter.",
    )
    parser.add_argument(
        "--model-id",
        default=os.getenv("ORACLE_FINETUNE_MODEL_ID", DEFAULT_MODEL_ID),
        help="Hugging Face model id to load in 4-bit mode.",
    )
    parser.add_argument(
        "--dataset",
        type=Path,
        default=DEFAULT_DATASET_PATH,
        help="Chat JSONL dataset generated by the fine-tune data script.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory where the LoRA adapter and tokenizer are saved.",
    )
    parser.add_argument("--max-seq-length", type=int, default=DEFAULT_MAX_SEQ_LENGTH)
    parser.add_argument("--max-steps", type=int, default=DEFAULT_MAX_STEPS)
    parser.add_argument(
        "--num-train-epochs",
        type=float,
        default=DEFAULT_NUM_TRAIN_EPOCHS,
        help="Number of full dataset epochs when --max-steps is negative.",
    )
    parser.add_argument("--batch-size", type=int, default=1)
    parser.add_argument("--grad-accumulation", type=int, default=8)
    parser.add_argument("--learning-rate", type=float, default=2e-4)
    parser.add_argument("--warmup-steps", type=int, default=5)
    parser.add_argument("--logging-steps", type=int, default=1)
    parser.add_argument("--save-steps", type=int, default=30)
    parser.add_argument("--seed", type=int, default=3407)
    parser.add_argument("--lora-rank", type=int, default=16)
    parser.add_argument("--lora-alpha", type=int, default=16)
    parser.add_argument("--lora-dropout", type=float, default=0.0)
    parser.add_argument(
        "--chat-template",
        default=DEFAULT_CHAT_TEMPLATE,
        choices=("gemma-4", "gemma-4-thinking"),
        help="Gemma 4 chat template used before SFT formatting.",
    )
    parser.add_argument(
        "--include-multimodal",
        action="store_true",
        help="Load multimodal encoders too. Default is text-only style SFT.",
    )
    parser.add_argument(
        "--offload-embedding",
        action="store_true",
        help="Offload large embedding layers to CPU when GPU memory is tight.",
    )
    parser.add_argument(
        "--gpu-memory-utilization",
        type=float,
        default=DEFAULT_GPU_MEMORY_UTILIZATION,
        help="Requested GPU memory utilization for Unsloth loader.",
    )
    parser.add_argument(
        "--min-vram-gb",
        type=float,
        default=DEFAULT_MIN_VRAM_GB,
        help="Minimum GPU VRAM expected before E2B QLoRA is attempted.",
    )
    parser.add_argument(
        "--allow-low-vram",
        action="store_true",
        help="Attempt training even when GPU VRAM is below --min-vram-gb.",
    )
    parser.add_argument(
        "--target-module",
        action="append",
        dest="target_modules",
        help="LoRA target module. Can be repeated.",
    )
    parser.add_argument(
        "--hf-token",
        default=os.getenv("HF_TOKEN"),
        help="Hugging Face token, if the base model requires one.",
    )
    parser.add_argument(
        "--merge-16bit-output-dir",
        type=Path,
        help="Optional directory for a merged 16-bit model.",
    )
    parser.add_argument(
        "--gguf-output-dir",
        type=Path,
        help="Optional directory for Unsloth GGUF export.",
    )
    parser.add_argument(
        "--gguf-quantization",
        default="q4_k_m",
        help="Quantization method used when --gguf-output-dir is set.",
    )
    parser.add_argument(
        "--resume-from-checkpoint",
        default=None,
        help="Checkpoint path or true/false value accepted by Transformers.",
    )
    args = parser.parse_args(argv)
    return args


def _load_training_dependencies() -> dict[str, Any]:
    try:
        import unsloth  # noqa: F401
        import torch
        from datasets import load_dataset
        from trl import SFTConfig, SFTTrainer
        from unsloth import FastModel
        from unsloth.chat_templates import get_chat_template
        from unsloth.chat_templates import train_on_responses_only
    except ImportError as error:
        raise RuntimeError(
            "Fine-tune dependencies are missing. Install requirements-finetune.txt "
            "in a CUDA-capable environment before running QLoRA training.",
        ) from error

    dependencies: dict[str, Any] = {
        "torch": torch,
        "load_dataset": load_dataset,
        "SFTConfig": SFTConfig,
        "SFTTrainer": SFTTrainer,
        "FastModel": FastModel,
        "get_chat_template": get_chat_template,
        "train_on_responses_only": train_on_responses_only,
    }
    return dependencies


def _build_text_formatter(tokenizer: Any) -> Callable[[dict[str, Any]], dict[str, list[str]]]:
    def format_batch(batch: dict[str, Any]) -> dict[str, list[str]]:
        texts = [
            tokenizer.apply_chat_template(
                messages,
                tokenize=False,
                add_generation_prompt=False,
            ).removeprefix("<bos>")
            for messages in batch["messages"]
        ]
        formatted_row = {"text": texts}
        return formatted_row

    formatter = format_batch
    return formatter


def _build_training_arguments(args: argparse.Namespace, dependencies: dict[str, Any]) -> Any:
    torch = dependencies["torch"]
    training_arguments_type = dependencies["SFTConfig"]
    use_bf16 = bool(torch.cuda.is_available() and torch.cuda.is_bf16_supported())
    use_fp16 = bool(torch.cuda.is_available() and not use_bf16)
    training_args = training_arguments_type(
        output_dir=str(args.output_dir),
        dataset_text_field="text",
        max_length=args.max_seq_length,
        packing=False,
        per_device_train_batch_size=args.batch_size,
        gradient_accumulation_steps=args.grad_accumulation,
        warmup_steps=args.warmup_steps,
        max_steps=args.max_steps,
        num_train_epochs=args.num_train_epochs,
        learning_rate=args.learning_rate,
        fp16=use_fp16,
        bf16=use_bf16,
        logging_steps=args.logging_steps,
        save_steps=args.save_steps,
        optim="adamw_8bit",
        weight_decay=0.01,
        lr_scheduler_type="linear",
        seed=args.seed,
        report_to="none",
    )
    return training_args


def _build_lora_kwargs(args: argparse.Namespace) -> dict[str, Any]:
    lora_kwargs: dict[str, Any] = {
        "finetune_vision_layers": False,
        "finetune_language_layers": True,
        "finetune_attention_modules": True,
        "finetune_mlp_modules": True,
        "r": args.lora_rank,
        "lora_alpha": args.lora_alpha,
        "lora_dropout": args.lora_dropout,
        "bias": "none",
        "random_state": args.seed,
    }
    if args.target_modules is not None:
        lora_kwargs["target_modules"] = args.target_modules
    return lora_kwargs


def _get_total_vram_gb(torch_module: Any) -> float:
    total_vram_gb = 0.0
    if torch_module.cuda.is_available():
        device_properties = torch_module.cuda.get_device_properties(0)
        total_vram_gb = device_properties.total_memory / (1024**3)
    return total_vram_gb


def _validate_training_hardware(
    args: argparse.Namespace,
    dependencies: dict[str, Any],
) -> None:
    torch = dependencies["torch"]
    if not torch.cuda.is_available():
        raise RuntimeError("QLoRA training requires a CUDA-capable GPU.")

    total_vram_gb = _get_total_vram_gb(torch)
    if total_vram_gb < args.min_vram_gb and not args.allow_low_vram:
        raise RuntimeError(
            "Gemma 4 E2B QLoRA needs more GPU memory than this device exposes: "
            f"{total_vram_gb:.2f}GB available, {args.min_vram_gb:.2f}GB expected. "
            "Use --allow-low-vram to try anyway, or run on an 8GB+ GPU.",
        )


def _build_trainer(
    trainer_type: Any,
    model: Any,
    tokenizer: Any,
    train_dataset: Any,
    training_args: Any,
) -> Any:
    trainer_parameters = inspect.signature(trainer_type).parameters
    trainer_kwargs: dict[str, Any] = {
        "model": model,
        "train_dataset": train_dataset,
        "args": training_args,
    }
    if "tokenizer" in trainer_parameters:
        trainer_kwargs["tokenizer"] = tokenizer
    else:
        trainer_kwargs["processing_class"] = tokenizer
    trainer = trainer_type(**trainer_kwargs)
    return trainer


def train_qlora(args: argparse.Namespace) -> Path:
    if not args.dataset.exists():
        raise FileNotFoundError(f"dataset not found: {args.dataset}")

    dependencies = _load_training_dependencies()
    _validate_training_hardware(args, dependencies)
    fast_model = dependencies["FastModel"]
    get_chat_template = dependencies["get_chat_template"]
    train_on_responses_only = dependencies["train_on_responses_only"]
    load_dataset = dependencies["load_dataset"]
    trainer_type = dependencies["SFTTrainer"]

    model, tokenizer = fast_model.from_pretrained(
        model_name=args.model_id,
        max_seq_length=args.max_seq_length,
        dtype=None,
        load_in_4bit=True,
        full_finetuning=False,
        token=args.hf_token,
        text_only=not args.include_multimodal,
        offload_embedding=args.offload_embedding,
        gpu_memory_utilization=args.gpu_memory_utilization,
    )
    model = fast_model.get_peft_model(
        model,
        **_build_lora_kwargs(args),
    )
    tokenizer = get_chat_template(tokenizer, chat_template=args.chat_template)

    dataset = load_dataset("json", data_files=str(args.dataset), split="train")
    text_dataset = dataset.map(_build_text_formatter(tokenizer), batched=True)
    training_args = _build_training_arguments(args, dependencies)
    trainer = _build_trainer(
        trainer_type=trainer_type,
        model=model,
        tokenizer=tokenizer,
        train_dataset=text_dataset,
        training_args=training_args,
    )
    trainer = train_on_responses_only(
        trainer,
        instruction_part="<|turn>user\n",
        response_part="<|turn>model\n",
    )

    trainer.train(resume_from_checkpoint=args.resume_from_checkpoint)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    model.save_pretrained(args.output_dir)
    tokenizer.save_pretrained(args.output_dir)

    if args.merge_16bit_output_dir is not None:
        model.save_pretrained_merged(
            str(args.merge_16bit_output_dir),
            tokenizer,
            save_method="merged_16bit",
        )
    if args.gguf_output_dir is not None:
        model.save_pretrained_gguf(
            str(args.gguf_output_dir),
            tokenizer,
            quantization_method=args.gguf_quantization,
        )

    output_dir = args.output_dir
    return output_dir


def main(argv: Sequence[str] | None = None) -> None:
    args = _parse_args(argv)
    output_dir = train_qlora(args)
    print(f"[finetune-train] saved adapter to {output_dir}")
